### ISSUE TITLE
configure via appsettings: logEventsInBatchLimit failing

### ISSUE THREAD

**Issue by svenso** [FantasticFiasco/serilog-sinks-http#256] opened 2022-04-25 10:45 UTC
**Describe the bug**

When using appsettings to configure the http sink using the following configuration:
```  
"Serilog": {
    "WriteTo": [
      {
        "Name": "Http",
        "Args": {
          "requestUri": "http://127.0.0.10:9000/xx",
          "logEventsInBatchLimit": 10
        }
      }
    ]
  },
```
which exactly matches the sample in the "migration guide" causes the following error:

````
2022-04-25T10:38:19.7785126Z Unable to find a method called Http for supplied arguments: logEventsInBatchLimit, requestUri. Candidate methods are:
Http(requestUri, queueLimitBytes, logEventLimitBytes, logEventsInBatchLimit, batchSizeLimitBytes, period, textFormatter, batchFormatter, restrictedToMinimumLevel, httpClient, configuration)
````

**Expected behavior**

The configuration above should be equal to this working workaround:

```  
"Serilog": {
    "WriteTo": [
      {
        "Name": "Http",
        "Args": {
          "requestUri": "http://127.0.0.10:9000/xx",
          "queueLimitBytes": null,
          "logEventLimitBytes": null,
          "logEventsInBatchLimit": 10
        }
      }
    ]
  },
```

**Additional context**

I am using the following config: 
````
 var config = new LoggerConfiguration()
                .ReadFrom.Configuration(Configuration)
                .Enrich.WithProperty("service", Assembly.GetEntryAssembly().GetName().Name)
                .Enrich.WithProperty("version", Assembly.GetEntryAssembly().GetName().Version.ToString(4))
                .Enrich.WithMachineName()
                .Enrich.FromLogContext();
````
Following references:
````
<PackageReference Include="Serilog" Version="2.11.0" />
<PackageReference Include="Serilog.AspNetCore" Version="5.0.0" />
<PackageReference Include="Serilog.Enrichers.Environment" Version="2.2.0" />
<PackageReference Include="Serilog.Formatting.Compact" Version="1.1.0" />
<PackageReference Include="Serilog.Settings.Configuration" Version="3.3.0" />
<PackageReference Include="Serilog.Sinks.Console" Version="4.0.1" />
<PackageReference Include="Serilog.Sinks.Http" Version="8.0.0" />
````

And .NET 6

**Comment by FantasticFiasco** [comment] 2022-04-26 10:54
Thanks @svenso for the detailed issue! I'll look into it and report back.

**Comment by FantasticFiasco** [comment] 2022-04-26 21:29
I think the problem is twofold.

The first problem is that the [migration guide of #203 and #245](https://github.com/FantasticFiasco/serilog-sinks-http/blob/8762fdc3083844efb827ababd64e7a4928e30063/CHANGELOG.md?plain=1#L126) doesn't give an example of a situation where specifying `queueLimit` becomes mandatory.

The second problem is that a change in the changelog individually describe the change, with no respect to other changes in the release. I.e. when [documenting #171](https://github.com/FantasticFiasco/serilog-sinks-http/blob/8762fdc3083844efb827ababd64e7a4928e30063/CHANGELOG.md?plain=1#L249) the migration guide was correct, but then later on other changes in the release affected the very same migration. I'll see what I can do about that.

In closing, in your situation I think the following configuration would be the correct one:

```
"Serilog": {
    "WriteTo": [
      {
        "Name": "Http",
        "Args": {
          "requestUri": "http://127.0.0.10:9000/xx",
          "queueLimitBytes": null,
          "logEventsInBatchLimit": 10
        }
      }
    ]
  },
```

**Closed** 2022-05-08 07:19 UTC
Labels: bug

**Comment by FantasticFiasco** [comment] 2022-05-08 07:21
I've updated the change log, fixing incorrect migration guides. Thank you for reporting the issue!
