### ISSUE TITLE
Configuring sink via LoggerConfiguration.ReadFrom.Configuration()

### ISSUE THREAD

**Issue by kenchilada** [FantasticFiasco/serilog-sinks-http#8] opened 2017-04-07 14:00 UTC
I'm probably doing something wrong here, but I cannot get Http sink to work when configuring via the appSettings route.  Maybe this is simply not supported?

### Step 1: Describe your environment

.NET Core
  
#### Steps to reproduce:

1. Configure sink via `IConfigurationRoot`

```
    "Serilog": {
        "MinimumLevel": "Debug",
        "Using": [ "Serilog.Sinks.Http" ],
        "WriteTo": [
            {
                "Name": "Http",
                "Args": { "requestUri": "http://127.0.0.1:38421/" }
            }
     }
```

2. Feed above config to `(new LoggerConfiguration().ReadFrom.Configuration(...))`
3. Run
  
#### Observed results

* The Http sink is not present in the sinks collection and I receive no sort of error to troubleshoot
* Same configuration and code works with other sinks such as LiterateConsole
* The Http sink DOES work if I configure it via `.WriteTo.Http(...)` but we need per-environment configuration and would like it to work as other sinks
  
#### Expected results

* Expected configuration above to result in a `Serilog.Core.Logger` instance with an Http sink instance in the `_sinks` property.

**Comment by FantasticFiasco** [comment] 2017-04-07 14:42
Thanks for the very detailed issue!

I've actually never verified the sink to work with configuration, but that is of course something that must work. I'll look into it in the upcoming days.

Would you be able to test a beta before I officially release a new version?

**Comment by kenchilada** [comment] 2017-04-07 18:36
I actually figured out why it was ignored and got it to load the sink.  After some digging in `Serilog.Settings.Configuration` I see that it searches for extension methods in the sink assembly that take a `LoggerSinkConfiguration` as the first parameter.  Elsewhere it also only considers this method as a candidate if the parameters have a default value or were set in the configuration.  If these criteria are not met then `ConfigurationReader` just silently ignores your sink in the configuration.  There is surprisingly no warning or error of any sort when a configuration in `WriteTo:` section is invalid.

The reason the sink would not load is that `LoggerSinkConfigurationExtensions.Http()` has the `Options` parameter with no default value.  I changed this to default to null, then check for null and assign `new Options() if so.  This made `ConfigurationReader` match the method and pick it up and I was able to set `requestUri` via `Args:{}`.  That worked.

Obviously that is still not ideal since you can't set most of the settings.  So I wrote an additional `Http()` that takes all the options directly as parameters and then builds the `Options` instance from that and calls the existing `Http()` extension method (so it remains compatible with existing usage).  I did not implement `DurableHttp()` yet.

With my changes I am able to do this...

```
        "WriteTo": [
            {
                "Name": "Http",
                "Args": {
                    "requestUri": "http://127.0.0.1:38421/",
                    "batchPostingLimit": 1,
                    "formattingType": "Normal",
                    "eventBodyLimitBytes": 128000,
                    "period":  "00:00:03" 
                }
            }
      ]
```

I can clean up and submit if you're interested, or happy to help with any testing.

**Comment by FantasticFiasco** [comment] 2017-04-07 21:40
Good find!

We'll solve this one, I just need some time to get more familiar with `Serilog.Settings.Configuration`.

What I would like to investigate is whether they only support a flat JSON argument structure, or whether we can model the `Options` in JSON something like this:

```
{
"Name": "Http",
"Args": {
    "requestUri": "http://127.0.0.1:38421/",
    "options": {
        "batchPostingLimit": 1,
        "formattingType": "Normal",
        "eventBodyLimitBytes": 128000,
        "period":  "00:00:03" 
    }
}
```

I would also like to investigate whether the durable and the non-durable sink both are available when configuring using `Serilog.Settings.Configuration`. What in the JSON would indicate the extension method, is it the name?

**Comment by FantasticFiasco** [comment] 2017-04-10 19:29
I haven't fixed this issue yet, and it will take another couple of days, something else currently has a higher priority.

Am I currently blocking you? If so we can come up with a temporary solution that allows you to continue with your development while still keeping the HTTP sink configuration in the JSON settings file.

**Comment by kenchilada** [comment] 2017-04-11 22:53
> Am I currently blocking you? 

No rush!  I created a local fork with a fix and we'll update later.

> What I would like to investigate is whether they only support a flat JSON argument structure, or whether we can model the Options in JSON something like this:

I don't believe that would work directly.  I could be wrong, but `ConfigurationReader` treats the `Args:` section children as either having a non-null string value or otherwise it does recursion on the section.  I believe that is to allow things like Serilog.Sinks.Async to work.

> I would also like to investigate whether the durable and the non-durable sink both are available when configuring using Serilog.Settings.Configuration. What in the JSON would indicate the extension method, is it the name?

The `Using:` key specifies assemblies that will be searched for extension methods.  Any extension method that has a first parameter of type `LoggerSinkConfiguration` is considered.  If the method satisfies the paramter rules, it just gets called and is free t return any `LoggerConfiguration` instance.  So you could have one extension method that decides durable or non-durable, or have one extension method for each that has different parameters.

My fork has this method and then just configures a `new Options()` inside...

```
    public static LoggerConfiguration Http(this LoggerSinkConfiguration sinkConfiguration,
            string requestUri,
            int? batchPostingLimit,
            string period,
            long? eventBodyLimitBytes,
            string formattingType,
            LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum,
            IHttpClient httpClient = null)
    {
            var options = new Options();
            .....
            return sinkConfiguration.Http(requestUri, options, restrictedToMinimumLevel, httpClient);

    }
```
`

**Comment by FantasticFiasco** [comment] 2017-04-25 05:37
I am awaiting this [PR](https://github.com/serilog/serilog-settings-configuration/issues/53) before I start implementing official support for JSON based configuration.

**Comment by nblumhardt** [comment] 2017-04-26 08:18
@FantasticFiasco the issue you've linked is not a PR; I don't think there is likely to be movement on it for a while as we don't yet have a proposed design, nor any further feedback. Would implementing a specific extension method here, but marking it `[EditorBrowsable(EditorBrowsableState.Hidden)]` be a good workaround that doesn't pollute IntelliSense? Cheers!

**Comment by FantasticFiasco** [comment] 2017-04-26 15:04
@nblumhardt you are correct, I got it wrong when describing it as a PR. Your proposed solution is a good one, I will try it out.

I think the initiative of having an alternative solution to the problem is a dead fish in the water. I'll close the issue.

**Closed** 2017-06-17 21:28 UTC
